### ISSUE TITLE
infinite loop?! 

### ISSUE THREAD

**Issue by hellresistor** [luizm/action-sh-checker#10]
Hi.

Have tried today your action!

are not work properly, or my mistake?
[https://github.com/hellresistor/WorkFlowShell/runs/639392470?check_suite_focus=true](url)
![githubactionbad](https://user-images.githubusercontent.com/50468493/80892053-1e689000-8cc0-11ea-8494-61a116b51877.png)

my main.yml:
`name: ShellCheck
on:
  
  push:
    branches:
      - master
  pull_request:
    
jobs:
  shchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1004 # It is posible to exclude some shellcheck warnings.
        with:
          sh_checker_comment: true
          sh_checker_exclude: ".terraform ^dir/example.sh"`

**Comment by luizm** [comment]
Yes, it works.

@hellresistor Could you try using the version 0.1.3?

I will check the version 1.4 as well.

**Comment by hellresistor** [comment]
have setup as new file workflow. And Run! :D

Can check this Warning?
![githubactionbad](https://user-images.githubusercontent.com/50468493/80907257-7c6f9480-8d0d-11ea-8c31-c66c728e33cb.png)

Action link: https://github.com/hellresistor/WorkFlowShell/actions/runs/94299387
main.yml file: https://github.com/hellresistor/WorkFlowShell/blob/master/.github/workflows/main.yml

Well my script have a propose error. `eho.`  But dont tell where is error and not correct him. just say "have found errors" and do a cat of my&new script.

How can able to detect the lineerror like as Shellcheck does?

Thank you for fast answer

**Comment by hellresistor** [comment]
https://github.com/hellresistor/WorkFlowShell/blob/master/.github/workflows/newmain.yml

Well. Have disabled shfmt and force shellcheck.

Not get a github-action like show on Readme. :o or i not understand what this does? (can answer in PT languange ;) =

**Comment by hellresistor** [comment]
about mistake "ech" command insteat "echo" It is a ShellCheck issue. I am using this:
[https://github.com/hellresistor/WorkFlowShell/blob/master/.github/workflows/oriori.yml](url)

And still dont get the "ech" command error.

**Comment by hellresistor** [comment]
OK. have seen.
https://github.com/hellresistor/WorkFlowShell/runs/640542896?check_suite_focus=true

The code are right!!! but say are not

**Comment by luizm** [comment]
> The code are right!!! but say are not

Thank you for the examples and for explaining to me how you are testing.

My bad, there is a bug when shftm is disable.

@hellresistor  Could you test using the pre-release: v0.1.5?

**Comment by hellresistor** [comment]
Tested. not work (at all). See Above situations

resuming:
- `echo -e ${bkwhite}\\n\\n          LALAj      ${bld}${red}%@. \\n      bybyby                @@@.\\n${bkwhite}"`  -- Without Double-Quote Are detected! SC1009 ( O K ! )

- `eho -e "${bkwhite}\\n\\n          LALAj      ${bld}${red}%@. \\n      bybyby                @@@.\\n${bkwhite}"`  -- Not detect is not a "echo" or a existing/valid command .

**Comment by luizm** [comment]
> eho -e "${bkwhite}\\n\\n LALAj ${bld}${red}%@. \\n bybyby @@@.\\n${bkwhite}" -- Not detect is not a "echo" or a existing/valid command .

Shellcheck or shfmt doesn't validate if command exists or if it is valid, so this action will not detect it as well.

**Comment by hellresistor** [comment]
I Think create the Issue on wrong repository before :O I will check! Thank you. Can I use 0.1.5 version?

**Comment by luizm** [comment]
> I Think create the Issue on wrong repository before :O I will check! Thank you. Can I use 0.1.5 version?

Yes, thank you for report the problems

**Comment by hellresistor** [comment]
Vou usar seu workflow. Valeu!

And this is the [ShellCheck](https://github.com/koalaman/shellcheck/issues/1936) issue created.

**Comment by luizm** [comment]
Vlw :)

**Comment by hellresistor** [comment]
https://github.com/koalaman/shellcheck/issues/1936#issuecomment-623168668

**Comment by hellresistor** [comment]
Nothing to do ;) and with reason ;)
