### ISSUE TITLE
Empty message at Validating shell scripts

### ISSUE THREAD

**Issue by kenorb** [luizm/action-sh-checker#11]
- Build: [640768967](https://github.com/EA31337/EA-Tester/runs/640768967#step:4:9)

```
2020-05-03T16:23:48.4552672Z Validating shell scripts files using shellcheck
2020-05-03T16:23:48.4552829Z 
2020-05-03T16:23:50.0944257Z Cleaning up orphan processes
```

Similar to #8

Same when running with [`act`](https://github.com/nektos/act):

```
$  act -j ShellCheck
...
[Lint/ShellCheck]   🐳  docker run image=act-luizm-action-sh-checker-master:latest entrypoint=[] cmd=[]
| Validating shell scripts files using shellcheck
| 
[Lint/ShellCheck]   ❌  Failure - Shell Check
Error: exit with `FAILURE`: 1
```

**Comment by luizm** [comment]
I was doing some modifications in the script,  I'm still testing the pre-release 1.0.5, but Could you rebuild now?

@kenorb

**Comment by kenorb** [comment]
I've [rebuilt](https://github.com/EA31337/EA-Tester/runs/640808114#step:4:11), it still errors, but the message is opposite:

> All sh files found looks fine :)

**Comment by luizm** [comment]
🤦 ops, Could you try again? :)

**Comment by kenorb** [comment]
> 🤦 ops, Could you try again? :)

[It works now](https://github.com/EA31337/EA-Tester/runs/640899774#step:4:11), thanks.
