### ISSUE TITLE
a '\n' are executing instead readit causing SC2034 ERROR

### ISSUE THREAD

**Issue by hellresistor** [luizm/action-sh-checker#15]
Correct Code (Passed in ShellCheck)
`MyBalR=$(echo "$MyBal" | awk '{printf("%d\n",$1 + 0.5)}')`

Get this on action-sh-checker v0.1.5 (and4 too) (are doing the \n on checking instead read it)
````
MyBalR=$(echo "$MyBal" | awk '{printf("%d
",$1 + 0.5)}')
^----^ SC2034: MyBalR appears unused. Verify use (or export if used externally).
````

**Comment by luizm** [comment]
The error: SC2034 is not related with this break line "\n".

When shellcheck run over your script, it identifies the problem SC2034, and when sh-checker shows the output the character \n is converted to a new line.

**Comment by hellresistor** [comment]
Ok!

I tryed to say its this. See difference.

ShellCheck
![ShellCheck](https://user-images.githubusercontent.com/50468493/81127825-5dece180-8f37-11ea-842c-083e2d36e8a2.png)

Luiz checker
![louis-sh-checker](https://user-images.githubusercontent.com/50468493/81127826-5e857800-8f37-11ea-9e1c-3d8921fc76c2.png)


Exposing this. Is not a issue. more like a little bug

**Comment by luizm** [comment]
> Exposing this. Is not a issue. more like a little bug

I can't work on it right now, but I will. Thank you for the report.

**Comment by hellresistor** [comment]
no problem! ;)
