### ISSUE TITLE
[Question] Can only files with changes be checked?

### ISSUE THREAD

**Issue by flying-sausages** [luizm/action-sh-checker#27]
I'd like to only check the files that got changed in a PR. We have ~200 shell scripts in our server toolbox and a single unformatted/unshellchecked file will mark a PR as a fail, regardless of it being touched or not.

Is there a way to do this currently? If not, would it be possible to only check files which are listed in the diff of the PR against the branch it is being merged into?

Thanks in advance!

**Comment by luizm** [comment]
Hey @flying-sausages .. unfortunately not yet..

But I think I can do it until next week

**Comment by flying-sausages** [comment]
No rush, just niceties ;)

**Comment by alan-barzilay** [comment]
any updates on this? @luizm

**Comment by luizm** [comment]
not yet.. to be honest, no free time to work on it.. 😞
