### ISSUE TITLE
feat: add shfmt parameters as optional inputs

### ISSUE THREAD

**Issue by luizm** [luizm/action-sh-checker#3]

**Comment by jkroepke** [comment]
👍 
Since shfmt doesn't have [config file support](https://github.com/mvdan/sh/issues/234), this would be great.

**Comment by MaxPeal** [comment]
shfmt implemented EditorConfig support instead - see https://github.com/mvdan/sh/issues/393 and the [docs](https://github.com/mvdan/sh/blob/master/README.md)

@luizm can you add a support for this in the action?

**Comment by luizm** [comment]
> @luizm can you add support for this in the action?

Nice @MaxPeal 

I think the only thing that we need to do is to update the shfmt version, and then it will check if the editorConfig exist and use then.

**Comment by MaxPeal** [comment]
BTW can you also add a shfmt parameters as optional args, like the SHELLCHECK_OPTS?

**Comment by luizm** [comment]
> BTW can you also add a shfmt parameters as optional args, like the SHELLCHECK_OPTS?

Yep, I will do that during this week :)

**Comment by IceCodeNew** [comment]
Would be great to see this improved in the next few days!
@luizm

**Comment by luizm** [comment]
@IceCodeNew could you try this pre-release: https://github.com/luizm/action-sh-checker/releases/tag/v0.1.8?

**Comment by IceCodeNew** [comment]
> @IceCodeNew could you try this pre-release: [`v0.1.8` (release)](https://github.com/luizm/action-sh-checker/releases/tag/v0.1.8)?

It works fine here, thank you for saving my day!
