### ISSUE TITLE
SHELLCHECK_OPT is not used anywhere

### ISSUE THREAD

**Issue by thibaultserti** [luizm/action-sh-checker#34]
SHELLCHECK_OPT is not used anywhere so we can't pass any options to shellcheck ...

**Comment by luizm** [comment]
We don't need to use, we just set it as env to be used as default by shellcheck

https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#environment-variables

**Comment by thibaultserti** [comment]
Ok thanks sorry for that !

**Comment by luizm** [comment]
> Ok thanks sorry for that !

:) No problem
