### ISSUE TITLE
shfmt does not fail anymore

### ISSUE THREAD

**Issue by haraldh** [luizm/action-sh-checker#44]
The `-d` option got lost in https://github.com/luizm/action-sh-checker/pull/40
https://github.com/luizm/action-sh-checker/blob/1be1f45b8dd9b397c67e636de1cc9a034459f358/entrypoint.sh#L158

CC: @rasa

**Comment by luizm** [comment]
https://github.com/luizm/action-sh-checker/releases/tag/v0.2.2
