### ISSUE TITLE
Add checkbashisms

### ISSUE THREAD

**Issue by jkroepke** [luizm/action-sh-checker#5]
Sometime it's important to run checkbashisms for portable / posix compatible shell scripts.

checkbashisms can be installed on debian based dists via:
```
apt-get install -qq devscripts
```

There is also a package on alpine repository: https://pkgs.alpinelinux.org/package/edge/main/x86/checkbashisms

**Comment by luizm** [comment]
@jkroepke, It's sounds good I will check to include it as an optional parameter.  Thank you for the suggestion
